#!/usr/bin/env python3

#
# create-domjudge-credentials-mails --from a teams CSV file generate credential emails in a directory    
#

import csv
import argparse


parser = argparse.ArgumentParser(description="from a teams CSV file generate credential emails in a directory")

parser.add_argument("EXTENDED_TEAMS_CSV_FILE",help='CSV file with "login","names","emails","password","team-category" header.')
args = parser.parse_args()

teams_csv_file=args.EXTENDED_TEAMS_CSV_FILE

# input csv file must have a header
teams_csv_file_handle = open(teams_csv_file, 'rt')
reader = csv.DictReader(teams_csv_file_handle, delimiter=",",  quotechar='"', quoting=csv.QUOTE_NONNUMERIC,skipinitialspace=True)
# note: skipinitialspace makes the reader to ignore spaces around delimiter

# getting rows; each row is a dictionary
rows=[]
for row in reader:
    rows.append(row)

# checking headers 
fieldnames = ["login","names","emails","password","team-category"]
headers=rows[0].keys()
for idx, fieldname in enumerate(fieldnames):
    if fieldname not in headers:
        print("ERROR: missing header '" +  fieldname + "'")
        exit(1)  

