#!/bin/bash


DOMJUDGE_VERSION="$1"
# note: domjudge has one domserver image and one judgehost image
#       domjudge requires the versions of the domserver and judgehost images match

if [[ -z "$DOMJUDGE_VERSION" ]]
then 
  echo "usage: domjudge-language-versions DOMJUDGE_VERSION"
  echo ""
  echo "description: checking language versions on docker image domjudge/judgehost:DOMJUDGE_VERSION"
  echo ""              
  exit 
fi

printf "\nchecking language versions on docker image domjudge/judgehost:$DOMJUDGE_VERSION\n\n"

docker run --rm -it --entrypoint bash --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro  domjudge/judgehost:$DOMJUDGE_VERSION\
             /opt/domjudge/judgehost/bin/dj_run_chroot \
             "echo "" &&  pypy3 --version && echo "" && javac --version && echo "" && gcc --version && g++ --version"
  
